### ISSUE TITLE
eigen moved to gitlab

### ISSUE THREAD

**Issue by benmkw** [mesonbuild/eigen#7]
```
[wrap-file]
directory = eigen-eigen-323c052e1731

source_url = https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.bz2
source_filename = eigen-eigen-323c052e1731.tar.bz2
source_hash = 685adf14bd8e9c015b78097c1dc22f2f01343756f196acdc76a678e1ae352e11

patch_url = https://wrapdb.mesonbuild.com/v1/projects/eigen/3.3.7/2/get_zip
patch_filename = eigen-3.3.7-2-wrap.zip
patch_hash = 7bd1f1eab1a7d5d43649ff5ed8a6101cc1e0dd99b2504a296b627696b2c8703a
```

does not work though cause it seems like the folder layout maybe has changed and meson can't find the folders?

**Comment by legeana** [comment]
Could you please submit a pull request?

**Comment by benmkw** [comment]
So the current issue is that the pasted config fails with `../subprojects/eigen-eigen-323c052e1731/meson.build:3:0: ERROR: File Eigen/PardisoSupport does not exist.`

I changed `source_url` and `source_hash` from the original wrap file and this is the complete error:

```
Downloading eigen source from https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.bz2
Using eigen patch from cache.

Executing subproject eigen method meson 

None of 'PKG_CONFIG_PATH' are defined in the environment, not changing global flags.
None of 'PKG_CONFIG_PATH' are defined in the environment, not changing global flags.
Project name: eigen
Project version: 3.3.7
C++ compiler for the build machine: /usr/bin/clang++ (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")
C++ linker for the build machine: /usr/bin/clang++ ld64 450.3
C++ compiler for the host machine: /usr/bin/clang++ (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")
C++ linker for the host machine: /usr/bin/clang++ ld64 450.3

../subprojects/eigen-eigen-323c052e1731/meson.build:3:0: ERROR: File Eigen/PardisoSupport does not exist.

```
where `Eigen/PardisoSupport` is just the first file in the meson.build file in the patch download so it seems like it just for some reason can't find the source/ the patch does not seem to apply correctly. So i'm note sure how to fix that yet in order to make that a working PR.

**Comment by legeana** [comment]
I am sorry for not being specific. The reason I asked you to submit a pull request is I have [a tool ](https://github.com/mesonbuild/mesonwrap/blob/master/mesonwrap/tools/reviewtool.py) that is really convenient to use on a pull request. It might help me to diagnose the problem. Also it will be much easier to just fix the problem and merge it.

**Comment by benmkw** [comment]
ok thanks :)
